### PR TITLE
Update ICONex connect README

### PR DESCRIPTION
**Pull request by bkbooth**
- Add CANCEL_SIGNING response
- Fix RESPONSE_HAS_ACCOUNT response
- Fix RESPONSE_ADDRESS response

### CODE REVIEW

**Comment by bkbooth** [comment]
I noticed a few discrepancies with the ICONex connect docs and the actual responses.

**Comment by jorisvial** [comment]
Closing because it's way too old now. Feel free to re-open a new PR if you feel like those changes are still required.

**Comment by bkbooth** [comment]
@jorisvial yeah, these changes are still required. The ICONex connect spec is still outdated, not sure why this was never merged. I'll open a new PR, the `CANCEL_JSON-RPC` response is also missing.

As far as I can tell, this is the "source of truth" doc for the ICONex connect spec? Even though I believe ICONex is being deprecated, the ICONex connect spec is still the official spec for how ICON dApps should interact.

**Comment by bkbooth** [comment]
Re-opened as #45

**Pull request closed without merging**
